name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'windows-latest'
            java: 11
          - os: 'ubuntu-latest'
            java: 11
          - os: 'macos-latest'
            java: 11
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository using v4
        uses: actions/checkout@v4


      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'sbt'

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Run tests
        run: sbt test
